-- 05_tasks.sql
-- Snowflake Tasks for automation

CREATE OR REPLACE TASK CRI.CRI_PROD_MARCUS.refresh_pd_downstreams_daily
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AS
BEGIN
  ALTER DYNAMIC TABLE CRI.CRI_WEBSITE_DATA.DT_THOMSON_REUTERS_COMPANY_CLIENT_DATA REFRESH;
  ALTER DYNAMIC TABLE CRI.CRI_PROD_MARCUS.DT_PD_COMPANY_INDIVIDUAL_DAILY_COMPLETE_LATEST_2D REFRESH;
  ALTER DYNAMIC TABLE CRI.CRI_WEBSITE_DATA.DT_PD_COMPANY_WEBSITE_DATA REFRESH;
  ALTER DYNAMIC TABLE CRI.CRI_WEBSITE_DATA.DT_PDIR_COMPANY_WEBSITE_DATA REFRESH;
  ALTER DYNAMIC TABLE CRI.CRI_WEBSITE_DATA.dt_credit_events_enriched REFRESH;
END;

-- (Add other tasks as in your docs)